4.6.0 (#204)
* Update tests

* Add automatic translation upload to deploy script

* Improve test coverage

* Improve test coverage

* Changes...

- Update mEDRA API call to their newly updated client-side API.
- Remove pointless `preventDefault` call on ReferenceList.
- Update deps.

* Fix tooltip issue on Firefox and Safari

* Changes...

- Convert all CSS to BEM methodology + maintain backwards compatibility
for old CSS classes.
- Add tests for Frontend.ts
- Fix issue causing tooltips to not render on Firefox or Safari.
- Change to "click" style tooltips, rather than hover style (better user
experience).
- Minor style changes to tooltips.
- Improve / refactor Frontend.ts code.

* Changes...

- Update dependencies.
- Add stylint to test workflow.
- Lint all styl files.

* Remove unnecessary variable from stylus vars

* Remove unneeded dependencies

* Remove unnecessary dependency

* Changes...

- Convert project to yarn package manager.
- Update travis.yml for yarn
- Move "lint" into npm test script
- Add yarn.lock to source control

* Remove ".abt-url" reference from options-page

* Add inline citation style example

* Add the following styles

- Aix-Marseille Université - Département d'études asiatiques (French)
- Uppsala universitet - Historia

* Build release 4.6.0

* Update readme with donor link

* Add donation link to options page

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -8,6 +8,47 @@ SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 ROOTDIR=$(cd "$SCRIPTDIR" && cd ../ && pwd || exit)
 SVNROOT=$(cd "$ROOTDIR" && cd ../SVN && pwd || exit)
 
+# shellcheck source=../.env
+source "$ROOTDIR/.env"
+
+# Helpers
+TERM=${TERM:-xterm}
+RED='\033[0;31m'
+ORANGE='\033[0;33m'
+CYAN='\033[0;36m'
+BOLD='\E[1m'
+NC='\033[0m'
+h2() {
+    echo -e "${ORANGE}${BOLD}==>${NC}${BOLD} $*${NC}"
+}
+h3() {
+    printf "%b \n" "${CYAN}${BOLD}  ->${NC} $*"
+}
+
+ERROR() {
+  echo -e "${RED}=> ERROR: $1.${NC}"
+  exit 1
+}
+
+PO_EDITOR_TOKEN=${PO_EDITOR_TOKEN:-}
+[[ ! $PO_EDITOR_TOKEN ]] && ERROR "'PO_EDITOR_TOKEN' must be set in your .env file"
+
+# Push updated translations to POEditor
+h2 "Updating POEditor translation strings"
+req=$(curl -X POST \
+     -F api_token="$PO_EDITOR_TOKEN" \
+     -F action="upload" \
+     -F id="68585" \
+     -F updating="terms" \
+     -F file=@"$ROOTDIR/src/academic-bloggers-toolkit.pot" \
+     https://poeditor.com/api/)
+
+h2 Status: "$(echo "$req" | jq -r '.response.status')"
+h3 Terms Parsed: "$(echo "$req" | jq -r '.details.terms.parsed')"
+h3 Terms Added: "$(echo "$req" | jq -r '.details.terms.added')"
+h3 Terms Deleted: "$(echo "$req" | jq -r '.details.terms.deleted')"
+exit
+
 # Make sure svn repo is up to date
 cd "$SVNROOT" || exit
 svn up
@@ -24,7 +65,12 @@ cp -r "$ROOTDIR"/dist/* "$SVNROOT"/tags/"$VERSION"/
 
 # Create a zipped copy of dist in ROOTDIR/tmp/bin
 rm -f "$ROOTDIR"/tmp/bin/*
-zip -r "$ROOTDIR"/tmp/bin/academic-bloggers-toolkit-"$VERSION".zip "$ROOTDIR"/dist
+mkdir -p "$ROOTDIR"/tmp/bin/academic-bloggers-toolkit
+cp -r "$ROOTDIR"/dist/* "$ROOTDIR"/tmp/bin/academic-bloggers-toolkit
+cd "$ROOTDIR"/tmp/bin || exit
+zip -r "$ROOTDIR"/tmp/bin/academic-bloggers-toolkit-"$VERSION".zip academic-bloggers-toolkit
+rm -r academic-bloggers-toolkit
+cd "$SVNROOT" || exit
 
 # Remove deleted files
 svn stat | grep -Po '^!.+' | awk '{print $2}' | xargs svn rm
